[package]
name = "auth"
version = "2.0.0"
authors = ["Vladimir Burdukov <chippcheg@gmail.com>"]
edition = "2021"

[dependencies]
security-framework-sys = { version = "2.0", default-features = false }
core-foundation = "0.9.2"
rpassword = "4.0"

[dev-dependencies]
dirs = "2.0"
